Feature/ending credit
sdp24-2-CodingPing/Invaders-SDP pull request #20
Opened 2024-10-04 14:49 UTC by bheeyo

### 변경 사항 요약

- creditlist 외부 리소스 추가
- FileManager에 loadCreditList 메소드 추가 및 구성
- DrawManager에 drawEndingCredit 메소드 추가 및 구성
- CreditScreen 클래스 생성 및 구성
- **크레딧 글자가 아래에서 위로 올라가게 구현함**

### 비고

- 현재 엔딩 크래딧의 마지막 글자까지 사라질 때 약 50초 소요.
- 외부 리소스인 creditlist에 형식을 미리 적어두어 다른 팀의 수정이 용이하게 함.

### 데모 영상

- ending credit 화면을 여는 장면

https://github.com/user-attachments/assets/3e123d68-69a3-48ed-ba0a-bbbb59ed8ea3

- ending credit 화면이 끝나고 자동으로 메인으로 돌아가는 장면

https://github.com/user-attachments/assets/4e8d236c-515f-4540-9546-7ebbdc5fe571

CSE2024SDP-90

2024-10-04 16:35 UTC, PIut0 requested changes
Commit이 중복되어 2개씩 Commit 되어 있습니다. 수정해야 할 것 같습니다..!

2024-10-04 16:35 UTC, PIut0 commented on src/screen/CreditScreen.java
> +        if (inputManager.isKeyDown(KeyEvent.VK_SPACE)
Space가 아닌 ESC를 누를 시 이동하도록 수정 부탁드리겠습니다..!

2024-10-05 19:30 UTC, PIut0 approved these changes
코드에는 문제가 없고, Commit Message가 잘못 되어있거나 Rebase 과정에서 중복 Commit 이 생긴 상태라, Squash Merge 방식으로 Commit 내역만 정리하면 괜찮을 것 같습니다.

2024-10-05 19:34 UTC, merged

2024-10-06 03:15 UTC, bheeyo commented
네 감사합니다!!