Refactor/player ship
sdp24-2-CodingPing/Invaders-SDP pull request #34
Opened 2024-11-16 18:47 UTC by PIut0

- Ship Class 를 기반으로 PlayerShip Class 생성
- 기존 GameScreen에서 관리하는 Player 정보를 PlayerShip Class 에서 관리하도록 리팩토링
- GameScreen 에서 비효율적으로 사용되던 GameState 객체를 사용하도록 리팩토링
- ShipLevelManager 클래스를 PlayerLevel 클래스로 변경 및 PlayerShip 에서 관리하도록 변경

[CSE2024SDP-165](https://plut0.atlassian.net/browse/CSE2024SDP-165)

2024-11-17 09:28 UTC, raewoo0908 requested changes
주말동안 작업에 감사드립니다.

코멘트 남긴 부분들만 수정해주신다면, 성공적으로 머지 가능할 것으로 보입니다. 

감사합니다.!

2024-11-17 09:28 UTC, raewoo0908 commented on src/entity/player/PlayerLevel.java
> +     * @param level particular level that you want to figure out how many EXP is required to get that level
아래 사항을 반영하여 수정 요청드립니다 !

1. "현재 레벨에서 한 단계 위의 레벨로 가기 위한 경험치"를 리턴하는 메서드라는 것을 더 직관적으로 표현하는 메서드 이름으로 수정.
2. param의 주석을 1. 에 맞는 표현으로 수정.

2024-11-17 09:28 UTC, raewoo0908 commented on src/entity/player/PlayerLevel.java
> +    // 각 레벨에 필요한 경험치를 저장하는 배열 (예: level 1 -> 100 exp, level 2 -> 200 exp)
"현재 레벨에서 한 단계 위로 가기 위한 경험치를 담고 있는 배열"임을 더 확실히 말할 수 있는 주석으로 수정이 필요합니다 !

2024-11-17 09:28 UTC, raewoo0908 commented on src/entity/player/PlayerLevel.java
> +            this.exp -= this.getRequiredExpForLevel(this.level);
경험치가 음수가 되는 버그가 발생했습니다. 41번과 42번 코드의 순서 변경을 요청드립니다!

2024-11-17 09:28 UTC, raewoo0908 commented on src/entity/player/PlayerLevel.java
> +        this.exp = exp;
"경험치를 추가한 후의 현재 경험치"를 로그로 볼 수 있게 추가 부탁드립니다.

2024-11-17 09:28 UTC, raewoo0908 commented on src/entity/player/PlayerLevel.java
> +        }
"레벨업 후의 레벨과 잔여 경험치"를 보여줄 수 있는 로그 추가 부탁드립니다. !

2024-11-17 12:25 UTC, PIut0 commented on src/entity/player/PlayerLevel.java
> +        this.exp = exp;
해당 log 는 PlayerShip 클래스에서 추가해두었습니다

2024-11-18 08:43 UTC, raewoo0908 approved these changes
LGTM :)

2024-11-18 11:39 UTC, merged