Feat/hud update
sdp24-2-CodingPing/Invaders-SDP pull request #56
Opened 2024-11-28 18:47 UTC by ilranarli

<HP, EXP와 HUD 연동 기능 추가>
- HP, EXP 바에 현재 HP, EXP 연동
- 스킬 3개 UI 삭제, 그 자리에 유저 스탯 UI 추가

CSE2024SDP-202

![이미지 2024  11  29  오후 6 06](https://github.com/user-attachments/assets/d6d4841d-e0b4-4aa9-a2fe-553c25a995cb)

2024-11-28 18:48 UTC, dayeondev commented
✅ **테스트 성공**

- 총 테스트: 5개
- 성공: 5개
- 실패: 0개
- 에러: 0개
- 스킵됨: 0개

모든 테스트를 성공적으로 통과했습니다! 🎉

2024-11-29 07:15 UTC, dayeondev commented
✅ **테스트 성공**

- 총 테스트: 5개
- 성공: 5개
- 실패: 0개
- 에러: 0개
- 스킵됨: 0개

모든 테스트를 성공적으로 통과했습니다! 🎉

2024-11-29 11:29 UTC, dayeondev commented
✅ **테스트 성공**

- 총 테스트: 5개
- 성공: 5개
- 실패: 0개
- 에러: 0개
- 스킵됨: 0개

모든 테스트를 성공적으로 통과했습니다! 🎉

2024-11-29 11:46 UTC, dayeondev approved these changes
코드 확인했습니다. 동작도 잘 되고, value 모아서 작업해주신 부분 등 포함해서 전체적으로 깔끔하고 좋아보입니다.
수고하셨습니다 :)

컨플릭트는 모든 히스토리 대조하며 진행해서 이슈 없을겁니다.

https://github.com/user-attachments/assets/2bbe35a6-a869-4f9f-ada3-872efaf5f7ec

2024-11-29 12:10 UTC, dayeondev commented
✅ **테스트 성공**

- 총 테스트: 5개
- 성공: 5개
- 실패: 0개
- 에러: 0개
- 스킵됨: 0개

모든 테스트를 성공적으로 통과했습니다! 🎉

2024-11-29 16:23 UTC, raewoo0908 requested changes

2024-11-29 16:23 UTC, raewoo0908 commented on src/screen/GameScreen.java
> +        340, HUD_Y + HUD_MARGIN_TOP + 17 + 10, 240, 12, currentEXP, maxEXP, Color.YELLOW);
https://github.com/user-attachments/assets/b6b511aa-9148-4296-838a-4cce1aa1981e

해당 라인에서 발생하는 버그는 아니지만, 관련된 메서드에서 버그가 발생하는 것을 확인했습니다.

꽤 높은 레벨에서, EXP 바가 다 찼는데도 불구하고 레벨업되지 않는 버그입니다. 
바에서 비율로 색칠하는 로직에서 문제가 있는 것으로 생각됩니다.

2024-11-30 14:55 UTC, dayeondev commented
✅ **테스트 성공**

- 총 테스트: 5개
- 성공: 5개
- 실패: 0개
- 에러: 0개
- 스킵됨: 0개

모든 테스트를 성공적으로 통과했습니다! 🎉

2024-11-30 14:57 UTC, ilranarli commented on src/screen/GameScreen.java
> +        340, HUD_Y + HUD_MARGIN_TOP + 17 + 10, 240, 12, currentEXP, maxEXP, Color.YELLOW);
비율 부분 EXP바 크기에 맞춰 코드 수정했습니다. 제가 보기엔 해결된 것 같은데 확인 부탁드려요!

2024-12-01 03:28 UTC, raewoo0908 approved these changes

2024-12-01 03:28 UTC, raewoo0908 commented on src/screen/GameScreen.java
> +        340, HUD_Y + HUD_MARGIN_TOP + 17 + 10, 240, 12, currentEXP, maxEXP, Color.YELLOW);
네, 정상작동 확인하였습니다. 수고하셨어요 :)

2024-12-01 08:47 UTC, dayeondev commented
✅ **테스트 성공**

- 총 테스트: 5개
- 성공: 5개
- 실패: 0개
- 에러: 0개
- 스킵됨: 0개

모든 테스트를 성공적으로 통과했습니다! 🎉

2024-12-01 09:39 UTC, PIut0 approved these changes
LGTM :) UI 배치가 깔끔해서 보기가 좋네요!

2024-12-01 09:40 UTC, merged